### ISSUE TITLE
How do I restart docker container without pressing hue bridge sync button?

### ISSUE THREAD

**Issue by AlfaJackal** [mrusme/hue2influx#1]
Docker container works like a charm! Thank you for your work! 
Is there any way to restart the container without pressing the bridge sync button?

**Comment by mrusme** [comment]
Depending on how you run the container you could simply stop and start it with Docker's regular commands. It doesn't have an API endpoint to do so, if you were referring to that.

1 https://docs.docker.com/engine/reference/commandline/restart/
2 https://docs.docker.com/compose/reference/restart/
3 https://docs.docker.com/engine/reference/commandline/service_update/

**Comment by mrusme** [comment]
In case you're referring to the fact that you always have to press the bridge after a restart: Simply make the user's home persistent by mounting a volume into your container. It will store the dot file that gets created on Hue auth (press) and use that next time it starts. :)

**Comment by mrusme** [comment]
Example:

```
docker service create \
--name hue2influx \
--hostname hue2influx \
--network yournet \
--mode global \
--env HUE_BRIDGE=yourbridge \
--env INFLUXDB_SERVER=yourinflux \
--env INFLUXDB_DB=yourdb \
--mount type=bind,source=/persistent/storage/hue2influx,target=/root,readonly=false \
mrusme/hue2influx
```
